name: clone_nexflix
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/NETFLIX_LOGO.png
     - assets/images/Netflix_N_logo.png
     - assets/images/A_Series_of_Unfortunate_Evants_01.png
     - assets/images/A_Series_of_Unfortunate_Evants_02.png
     - assets/images/A_Series_of_Unfortunate_Evants_03.png
     - assets/images/A_Series_of_Unfortunate_Evants_04.png
     - assets/images/A_Series_of_Unfortunate_Evants_05.png
     - assets/images/A_Series_of_Unfortunate_Evants_06.png
     - assets/images/A_Series_of_Unfortunate_Evants_07.png
     - assets/images/A_Series_of_Unfortunate_Evants_08.png
     - assets/images/A_Series_of_Unfortunate_Evants_09.png
     - assets/images/Ask_the_StoryBots_01.png
     - assets/images/Ask_the_StoryBots_02.png
     - assets/images/Ask_the_StoryBots_03.png
     - assets/images/Ask_the_StoryBots_04.png
     - assets/images/Ask_the_StoryBots_05.png
     - assets/images/Ask_the_StoryBots_06.png
     - assets/images/Black_Mirror_01.png
     - assets/images/Black_Mirror_02.png
     - assets/images/Black_Mirror_03.png
     - assets/images/Black_Mirror_04.png
     - assets/images/Black_Mirror_05.png
     - assets/images/Black_Mirror_06.png
     - assets/images/Black_Mirror_07.png
     - assets/images/Bright_01.png
     - assets/images/Bright_02.png
     - assets/images/Bright_03.png
     - assets/images/Carmen_Sandiego_01.png
     - assets/images/Carmen_Sandiego_02.png
     - assets/images/Carmen_Sandiego_03.png
     - assets/images/Carmen_Sandiego_04.png
     - assets/images/Carmen_Sandiego_05.png
     - assets/images/Carmen_Sandiego_06.png
     - assets/images/Carmen_Sandiego_07.png
     - assets/images/Carmen_Sandiego_08.png
     - assets/images/Carmen_Sandiego_09.png
     - assets/images/Carmen_Sandiego_10.png
     - assets/images/Carmen_Sandiego_11.png
     - assets/images/Carmen_Sandiego_12.png
     - assets/images/Carmen_Sandiego_13.png
     - assets/images/Disenchantment_01.png
     - assets/images/Disenchantment_02.png
     - assets/images/Disenchantment_03.png
     - assets/images/Disenchantment_04.png
     - assets/images/Disenchantment_05.png
     - assets/images/Disenchantment_06.png
     - assets/images/kids_01.png
     - assets/images/Larva_Island_01.png
     - assets/images/Larva_Island_02.png
     - assets/images/Larva_Island_03.png
     - assets/images/Larva_Island_04.png
     - assets/images/Larva_Island_05.png
     - assets/images/Larva_Island_06.png
     - assets/images/Larva_Island_07.png
     - assets/images/Larva_Island_08.png
     - assets/images/Larva_Island_09.png
     - assets/images/Lost_in_Space_01.png
     - assets/images/Lost_in_Space_02.png
     - assets/images/Lost_in_Space_03.png
     - assets/images/Lost_in_Space_04.png
     - assets/images/Lost_in_Space_05.png
     - assets/images/Lost_in_Space_06.png
     - assets/images/Lost_in_Space_07.png
     - assets/images/Lost_in_Space_08.png
     - assets/images/Lost_in_Space_09.png
     - assets/images/Money_Heist_01.png
     - assets/images/Money_Heist_02.png
     - assets/images/Money_Heist_03.png
     - assets/images/Money_Heist_04.png
     - assets/images/Money_Heist_05.png
     - assets/images/Money_Heist_06.png
     - assets/images/Money_Heist_07.png
     - assets/images/Money_Heist_08.png
     - assets/images/Money_Heist_09.png
     - assets/images/Orange_Is_the_New_Black_01.png
     - assets/images/Orange_Is_the_New_Black_02.png
     - assets/images/Orange_Is_the_New_Black_03.png
     - assets/images/Orange_Is_the_New_Black_04.png
     - assets/images/Orange_Is_the_New_Black_05.png
     - assets/images/Orange_Is_the_New_Black_06.png
     - assets/images/Orange_Is_the_New_Black_07.png
     - assets/images/Orange_Is_the_New_Black_08.png
     - assets/images/Orange_Is_the_New_Black_09.png
     - assets/images/Orange_Is_the_New_Black_10.png
     - assets/images/Our_Planet_01.png
     - assets/images/Our_Planet_02.png
     - assets/images/Our_Planet_03.png
     - assets/images/Our_Planet_04.png
     - assets/images/Our_Planet_05.png
     - assets/images/Our_Planet_06.png
     - assets/images/Our_Planet_07.png
     - assets/images/Our_Planet_08.png
     - assets/images/Our_Planet_09.png
     - assets/images/Our_Planet_10.png
     - assets/images/Our_Planet_11.png
     - assets/images/Our_Planet_12.png
     - assets/images/Our_Planet_13.png
     - assets/images/Our_Planet_14.png
     - assets/images/Queer_Eye_01.png
     - assets/images/Queer_Eye_02.png
     - assets/images/Queer_Eye_03.png
     - assets/images/Queer_Eye_04.png
     - assets/images/Queer_Eye_05.png
     - assets/images/Stranger_Things_01.png
     - assets/images/Stranger_Things_02.png
     - assets/images/Stranger_Things_03.png
     - assets/images/Stranger_Things_04.png
     - assets/images/Stranger_Things_05.png
     - assets/images/Stranger_Things_06.png
     - assets/images/Stranger_Things_07.png
     - assets/images/Stranger_Things_08.png
     - assets/images/Stranger_Things_09.png
     - assets/images/Stranger_Things_10.png
     - assets/images/Stranger_Things_11.png
     - assets/images/Stranger_Things_12.png
     - assets/images/Stranger_Things_13.png
     - assets/images/Stranger_Things_14.png
     - assets/images/Stranger_Things_15.png
     - assets/images/Stranger_Things_16.png
     - assets/images/The_Boss_Baby_Back_in_Business_01.png
     - assets/images/The_Boss_Baby_Back_in_Business_02.png
     - assets/images/The_Boss_Baby_Back_in_Business_03.png
     - assets/images/The_Boss_Baby_Back_in_Business_04.png
     - assets/images/The_Boss_Baby_Back_in_Business_05.png
     - assets/images/The_Boss_Baby_Back_in_Business_06.png
     - assets/images/The_Boss_Baby_Back_in_Business_07.png
     - assets/images/The_Boss_Baby_Back_in_Business_08.png
     - assets/images/The_Boss_Baby_Back_in_Business_09.png
     - assets/images/The_Boss_Baby_Back_in_Business_10.png
     - assets/images/The_Boss_Baby_Back_in_Business_11.png
     - assets/images/The_Classics_01.png
     - assets/images/The_Classics_02.png
     - assets/images/The_Classics_03.png
     - assets/images/The_Classics_04.png
     - assets/images/The_Classics_05.png
     - assets/images/The_Classics_06.png
     - assets/images/The_Classics_07.png
     - assets/images/The_Classics_08.png
     - assets/images/The_Classics_09.png
     - assets/images/The_Classics_10.png
     - assets/images/The_Classics_11.png
     - assets/images/The_Classics_12.png
     - assets/images/The_Classics_13.png
     - assets/images/The_Classics_14.png
     - assets/images/The_Classics_15.png
     - assets/images/The_Classics_16.png
     - assets/images/The_Classics_17.png
     - assets/images/The_Classics_18.png
     - assets/images/The_Crown_01.png
     - assets/images/The_Crown_02.png
     - assets/images/The_Crown_03.png
     - assets/images/The_Crown_04.png
     - assets/images/The_Crown_05.png
     - assets/images/The_Crown_06.png
     - assets/images/The_Crown_07.png
     - assets/images/The_Crown_08.png
     - assets/images/The_Dark_Crystal_Age_of_Resistance_01.png
     - assets/images/The_Dark_Crystal_Age_of_Resistance_02.png
     - assets/images/The_Dark_Crystal_Age_of_Resistance_03.png
     - assets/images/The_Dark_Crystal_Age_of_Resistance_04.png
     - assets/images/The_Dark_Crystal_Age_of_Resistance_05.png
     - assets/images/The_Dark_Crystal_Age_of_Resistance_06.png
     - assets/images/The_Dark_Crystal_Age_of_Resistance_07.png
     - assets/images/The_Dark_Crystal_Age_of_Resistance_08.png
     - assets/images/The_Dark_Crystal_Age_of_Resistance_09.png
     - assets/images/The_Dragon_Prince_01.png
     - assets/images/The_Dragon_Prince_02.png
     - assets/images/The_Dragon_Prince_03.png
     - assets/images/The_Dragon_Prince_04.png
     - assets/images/The_Dragon_Prince_05.png
     - assets/images/The_Dragon_Prince_06.png
     - assets/images/The_Dragon_Prince_07.png
     - assets/images/The_Dragon_Prince_08.png
     - assets/images/The_Dragon_Prince_09.png
     - assets/images/The_Dragon_Prince_10.png
     - assets/images/The_Dragon_Prince_11.png
     - assets/images/The_Dragon_Prince_12.png
     - assets/images/The_Witcher_01.png
     - assets/images/The_Witcher_02.png
     - assets/images/The_Witcher_03.png
     - assets/images/The_Witcher_04.png
     - assets/images/The_Witcher_05.png
     - assets/images/The_Witcher_06.png
     - assets/images/The_Witcher_07.png
     - assets/images/Trollhunters_Tales_of_Arcadia_01.png
     - assets/images/Trollhunters_Tales_of_Arcadia_02.png
     - assets/images/Trollhunters_Tales_of_Arcadia_03.png
     - assets/images/Trollhunters_Tales_of_Arcadia_04.png
     - assets/images/Trollhunters_Tales_of_Arcadia_05.png
     - assets/images/Trollhunters_Tales_of_Arcadia_06.png
     - assets/images/Trollhunters_Tales_of_Arcadia_07.png
     - assets/images/Trollhunters_Tales_of_Arcadia_08.png
     - assets/images/the_adam_project.png





  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
